project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/**/*.qmd"
  
website:
  page-navigation: true
  title: "Beyond {gtsummary}: How the {crane} Package Extends the Framework for Pharmaceutical Reporting"
  description: "Talk at R in Pharma 2025"
  favicon: "images/crane-hex.png"

  repo-url: https://github.com/ddsjoberg/RinPharma-crane-2025
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [@minecr.bsky.social](https://bsky.app/profile/minecr.bsky.social)."
    background: "#ffcee8"

  sidebar:
    background: "#ffcee8"
    logo: "images/crane-hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ddsjoberg/RinPharma-crane-2025
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: license.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

